config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  resources :tasks do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '会議' },
    { id: 3, name: '面談' },
    { id: 4, name: '外出' },
    { id: 5, name: '対応' },
    { id: 6, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :tasks
  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates :text, presence: { message: "を入力してください" }
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '対応前' },
    { id: 3, name: '対応中' },
    { id: 4, name: '対応済み' }
  ]

  include ActiveHash::Associations
  has_many :tasks
  end

app/models/task.rb
class Task < ApplicationRecord
  has_many :task_users, dependent: :destroy
  has_many :users, through: :task_users, validate: false
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :explanation, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :user_ids, presence: true

  validate :start_end_check
  #validate :start_check
  
  validates :category_id, numericality: { other_than: 1, message: "を選択してください" } 
  validates :condition_id, numericality: { other_than: 1, message: "を選択してください" } 
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :condition

  private

  def start_end_check
    if self.start_time == nil 
      errors.add(:start_time, "時間を入力してください")
    elsif self.end_time == nil
      errors.add(:end_time, "時間を入力してください")
    elsif self.start_time > self.end_time
      errors.add(:end_time, "は開始時刻より遅い時間を選択してください")
    end
  end

end

app/models/task_user.rb
class TaskUser < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :task_users
  has_many :tasks, through: :task_users
  has_many :comments, dependent: :destroy
  
  validates :nickname, presence: true
  validates :first_name, presence: true,format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
  validates :last_name, presence: true,format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }

  validates :password,format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource) 
    tasks_path
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:first_name,:last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @task = Task.find(params[:task_id]) #追加
    if @comment.save
      CommentChannel.broadcast_to @task, { comment: @comment, user: @comment.user } #追加
    else
      @error_comment = @comment
      render :error  
    end
  end

  def destroy
    @task = Task.find(params[:task_id])
    comment = @task.comments.find(params[:id])
    if current_user.id == comment.user.id
      comment.destroy
      redirect_to edit_task_path(params[:task_id])
    else
      redirect_to tasks_path
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, task_id: params[:task_id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:edit, :update,:destroy]
  before_action :set_users, only: [:index,:show]
  def index
    @user = User.find(current_user.id)
    @tasks  = @user.tasks
  end

  def show
    if User.exists?(params[:id])
      @user = User.find(params[:id])
      @tasks = @user.tasks
    else
      redirect_to tasks_path
    end
  end

  def new
    @task = Task.new
  end

  def create
    @user = current_user
    @task = @user.tasks.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
      @comments = @task.comments.includes(:user)
      @comment = Comment.new
  end

  def update
    if @task.users.includes(current_user)
      if @task.update(task_params)
        redirect_to tasks_path
      else
        render :edit
      end
    else
      redirect_to tasks_path
    end
  end

  def destroy
    if @task.users.includes(current_user)
      @task.destroy
      redirect_to  tasks_path
    else
      redirect_to tasks_path
    end
  end

  private

  def task_params
    params.require(:task).permit(:title,:explanation,:category_id,:condition_id,:start_time,:end_time,{:user_ids => []})
  end

  def set_task
    if Task.exists?(params[:id])
      @task = Task.find(params[:id])
    else
      redirect_to tasks_path
    end
  end

  def set_users
    @users = User.all
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/comments/error.js.erb
$("#comments-error").html("<%= j(render 'layouts/error_messages', model: @comment) %>");

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roadmap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/header' %> 

  <%# deivseのフラッシュメッセージを表示 %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="header">
  <div class="main_title">
    <%if !(current_page?(root_path)) && user_signed_in? %>
      <%= link_to "オンラインRoadmap", tasks_path, class: "link" %>
    <% else %>
      オンラインRoadmap
    <%end%>

  </div>
  <div class="header_link">
    <%if !(current_page?(root_path)) %>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <%= link_to "タスク登録", new_task_path ,class: "link"%>
          <%= current_user.nickname %>さん
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class: "link"%>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, class: "link" %>
          <%= link_to "新規登録", new_user_registration_path, class: "link" %>
        </div>
      <% end %>
    <%end%>
  </div>
</div>

app/views/tasks/_side_bar.html.erb
 <div class="users">
    <% User.where.not(id: current_user.id).each do |user| %>
      <div class="user">
        <div class="user-name">
          <%= link_to user.first_name + user.last_name , task_path(user.id), method: :get %>
        </div>
      </div>
    <% end %>
  </div>

app/views/tasks/edit.html.erb
<html>
<body>

<div class='task-edit-main'>
  <div class='task-edit-up'>
    <div class ='task-detail'>
      <h1>タスクの詳細です！</h1>
      <table border="1">
      <h3>タスク名: <%=@task.title%></h3>
      <tr><th>タスクの説明</th>
      <th><%=@task.explanation%></th></tr>
      <tr><th>タスクの状態</th>
      <th><%=@task.condition.name%></th></tr>
      <tr><th>タスクの種類</th>
      <th><%=@task.category.name%></th></tr>
      <tr><th>タスクの開始時間</th>
      <th><%=@task.start_time.to_s(:datetime_jp)%></th></tr>
      <tr><th>タスクの終了時間</th>
      <th><%=@task.end_time.to_s(:datetime_jp)%></th></tr>
      <tr><th>タスクの参加者</th>
      <th><%=@task.users.pluck(:first_name).join(", ")%></th></tr>
      </table>
    </div>
  </div>

<% if user_signed_in? && @task.users.pluck(:id).include?(current_user.id)  %>
  <div class='task-edit-down'>
  <h1>タスク編集画面です！</h1>
    <div class='task-from'>
      <%=form_with model: @task, local: true do |f|%>
      <%= render 'layouts/error_messages', model: f.object %>
        
        <%= f.label :title, :タスク名, class: 'task-form_label'%><br>
        <%= f.text_field :title, class: 'task_title_input', placeholder: 'タスク名を入力してください'%><br>

        <div class="items-explain">
          <div class="weight-bold-text">
            タスクの説明
            <span class="indispensable"></span><br>
          </div>
          <%= f.text_area :explanation, class:"task-text", id:"tasks-info", placeholder:"タスクの詳細"%><br>
        </div>

        <%= f.label :category_id, :タスクの種類, class: 'task-form_label'%><br>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"genre-select"}) %><br>
        
        <%= f.label :condition_id, :タスクの状態, class: 'task-form_label'%><br>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"genre-select"}) %><br>

        <%= f.label :start_time, :タスクの開始時間, class: 'task-form_label'%><br>
        <%= f.datetime_select :start_time, {use_month_numbers: true,minute_step: 15}, {class: 'time-box'}%><br>

        <%= f.label :end_time, :タスクの終了時間, class: 'task-form_label'%><br>
        <%= f.datetime_select :end_time, {use_month_numbers: true,minute_step: 15}, {class: 'time-box'}%><br>

        <label>タスクの参加者</label><br>
        <%= f.collection_check_boxes :user_ids, User.all, :id, :nickname %><br>

        <%= f.submit class: 'task-from_action'%>
      <% end %>
    </div>
    <h1>タスクの削除リンクです！</h1>
    <div class='task-de'>
      <div class='task-delete'>
        <%= link_to '・タスクを削除する', task_path(@task.id), method: :delete ,class: "link"%>
      </div>
    </div>
  </div>
  <%else%>
  <h3>参加者以外には編集・削除の権限はありません</h3>
  <% end %>
</div>

<div class="comments-main">
  <div class="comments-index">
    <div id="comments">
      <h4>＜コメント一覧＞</h4>
      <% @task.comments.each do |comment| %>
        <div class="comment">
          <p class="user-info"><%= comment.user.nickname %>： </p>
          <p><%= comment.text%></p>
          <% if user_signed_in? && current_user.id == comment.user_id%>
            <%= link_to 'コメントを削除', task_comment_path(@task, comment), confirm: 'Are you sure?', method: :delete, class: "link" %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="comment-form">
      <% if user_signed_in? %>
        <%= form_with model: [@task, @comment], id: "comment-form" do |f| %>

        <div id="comments-error">
        <%= render 'layouts/error_messages', model: f.object %>
        </div>
        
          <%= f.text_area :text , class: "comment-text"%>
          <%= f.submit "コメントをする", class: "comment-submit" %>
        <% end %>
      <% else %>
      ※※ログインしていないとコメントをすることができません※※
      <% end %>
    </div>
  </div>
</div>

</body>
</html>

app/views/tasks/index.html.erb
<div class="task_main">
  <div class="user_index">
    <%= render partial: "side_bar", locals: { user: @user } %>
  </div>

  <div class="user_calendar">
  <h1>1ヶ月のスケジュールです！</h1>
    <div id='calendar'></div>
  </div>
</div>

app/views/tasks/new.html.erb
<div>
<h1>タスク登録画面です！</h1>
  <div class='task-from_new'>
    
    <%=form_with model: @task, local: true do |f|%>
    <%= render 'layouts/error_messages', model: f.object %>
      
      <%= f.label :title, :タスク名, class: 'task-form_label'%><br>
      <%= f.text_field :title, class: 'task_title_input', placeholder: 'タスク名を入力してください'%><br>

      <div class="items-explain">
        <div class="weight-bold-text">
          タスクの説明<br>
        </div>
        <%= f.text_area :explanation, class:"task-text", id:"tasks-info", placeholder:"タスクの詳細"%><br>
      </div>

      <%= f.label :category_id, :タスクの種類, class: 'task-form_label'%><br>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"genre-select"}) %><br>
      
      <%= f.label :condition_id, :タスクの状態, class: 'task-form_label'%><br>
      <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"genre-select"}) %><br>

      <%= f.label :start_time, :タスクの開始時間, class: 'task-form_label'%><br>
      <%= f.datetime_select :start_time, {use_month_numbers: true,minute_step: 15}, {class: 'time-box'}%><br>

      <%= f.label :end_time, :タスクの終了時間, class: 'task-form_label'%><br>
      <%= f.datetime_select :end_time, {use_month_numbers: true,minute_step: 15}, {class: 'time-box'}%><br>

     <label>タスクの参加者</label><br>
      <%= f.collection_check_boxes :user_ids, User.all, :id, :nickname %><br>

      <%= f.submit class: 'task-from_action'%>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="task_main">
  <div class="user_index">
    <%= render partial: "side_bar", locals: { user: @user } %>
  </div>

  
  <div class="user_calendar">
  <h1><%= @user.nickname %>さんの1ヶ月のスケジュールです！</h1>
    <div id='onlyCalendar'></div>
  </div>
</div>

app/views/top/index.html.erb
<!DOCTYPE html>
<html>
<h3>オンラインroadmapトップページです!</h3><br>

    ログイン、または新規登録してください!
<div class="top-main">
    <div class="box-inner">
        <div class="box3">
        <div class="box-newusr">
        <%= link_to 'ログイン', new_user_session_path %>
        </div>

        <div class="box-newusr">
        <%= link_to '新規登録', new_user_registration_path%>
        </div>
        </div>
  </div>
</div>
</html>